name: example-pipline
on: pull_request

jobs:
  
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - id: set-matrix    
        run: |

          echo "::set-output name=matrix::matrix={\"container\":[{\"advanced-api/automatic-vendor-sharing\"},{\"advanced-api/dynamic-remotes\"}]}" 
     

  run-e2e-test:
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - run: echo 'Run test'


          

